apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvino-demo
  label:
    app: openvino-demo
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvino-demo
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: openvino-demo
        release: {{ .Release.Name }}
    spec:
      hostNetwork: true
      containers:
      - name: openvino-demo
        image: starlingx99/openvino-demo:latest
        imagePullPolicy: IfNotPresent
        command: ["top","-b"]
